export default dataBook = [
  {
    name: "Pain",
    id: "1",
    Village: "Hidden Rain",
    description: "Six Path of Pain",
    Village_Icon: require("../assets/img/rain_village_icon.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: "Uzumaki",
    color: "#ef5350",
    clan_Icon: require("../assets/img/uzumaki_logo.png"),
    img: require("../assets/img/pain-3.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Rinnegan",
        icon: require("../assets/img/rinnegan_logo.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2",name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Earth Release", icon: require("../assets/img/earth.png") },
      { id: "4", name: "Water Release", icon: require("../assets/img/water.png") },
      {  id: "5",name: "Wind Release", icon: require("../assets/img/wind.png") },
      { id: "6", name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Shisui",
    id: "2",
    Village: "Hidden Leef",
    description: "Shisui of the body flicker",
    color: "#009688",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Anbu",
    Afiliation_Icon: require("../assets/img/anbu.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: " uchiha",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/shisui.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },


  {
    name: "Jiraiya",
    id: "3",
    Village: "Hidden Leef",
    description: "Legendary Sami",
    color: "#827717",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Mount Myoboku",
    Afiliation_Icon: require("../assets/img/anbu.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/jiray.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Darui",
    id: "4",
    Village: "Hidden Leef",
    description: "The Black Lightning Panter",
    color: "#01579b",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Mount Myoboku",
    Afiliation_Icon: require("../assets/img/anbu.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/darui.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },
  {
    name: "Mei",
    id: "5",
    Village: "Hidden Mist",
    description: "Melt Kiss",
    color: "#f48fb1",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Mizukage",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Female",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/mei.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Kisame",
    id: "6",
    Village: "Hidden Mist",
    description: "The Shark",
    color: "#039be5",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "AKatski",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/kisame.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "KakaShi",
    id: "7",
    Village: "Hidden Leef",
    description: "The Copy Ninja",
    color: "#757575",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Forma Anbu",
    Afiliation_Icon: require("../assets/img/anbu.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/kakashi.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Deidara",
    id: "8",
    Village: "Hidden Stone",
    description: "Art is an Explosion",
    color: "#f9a825",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "S rank",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/deidara.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Naruto",
    id: "9",
    Village: "Hidden Leef",
    description: "Talk no jutsu",
    color: "#4a148c",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Kage",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Masculino",
    clan: " Uzumaki",
    clan_Icon: require("../assets/img/uzumaki_logo.png"),
    img: require("../assets/img/naruto.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Sasuke",
    id: "10",
    Village: "Hidden Leef",
    description: "The Avenger",
    color: "#3e2723",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/sasuke.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Itachi",
    id: "11",
    Village: "Hidden Leef",
    description: "The Patriote",
    color: "#b71c1c",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/itachi.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },
  {
    name: "Rock Lee",
    id: "12",
    Village: "Hidden Leef",
    description: "The Green Leef of the village",
    color: "#006064",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Masculino",
    clan: " Unkwon",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/lee.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Sakura",
    id: "13",
    Village: "Hidden Leef",
    description: "The Medical Ninja",
    color: "#f8bbd0",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "S rank",
    Gender: "Female",
    clan: " Haruno",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/sakura.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Hashirama",
    id: "14",
    Village: "Hidden Leef",
    description: "God of Shinobi",
    color: "#5d4037",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Male",
    clan: " Senju",
    clan_Icon: require("../assets/img/senju_logo.png"),
    img: require("../assets/img/hashirama.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Madara",
    id: "15",
    Village: "Hidden Leef",
    description: "God of Shinobi",
    color: "#900C3F",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Male",
    clan: " Uchiha",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/madara.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },
  {
    name: "Kakuzu",
    id: "16",
    Village: "Hidden Irion",
    description: "Bounty Hunter",
    color: "#28B463",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Male",
    clan: " Uchiha",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/kakuzu.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Shino",
    id: "17",
    Village: "Hidden Leef",
    description: "Master of Insects",
    color: "#00b8d4",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Male",
    clan: " Uchiha",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/shino.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },

  {
    name: "Kiba",
    id: "18",
    Village: "Hidden Leef",
    description: "Master of Insects",
    color: "#5D6D7E",
    Village_Icon: require("../assets/img/leef_village_logo.png"),
    Afiliation: "Akatsuki",
    Afiliation_Icon: require("../assets/img/akatsuki.png"),
    Ninja_Level: "Kage",
    Gender: "Male",
    clan: " Uchiha",
    clan_Icon: require("../assets/img/uchiha_logo.png"),
    img: require("../assets/img/kiba.png"),
    Kekkei_Genkais: [
      {
        id: "1",
        name: "Sharingan",
        icon: require("../assets/img/sharinga.png"),
      },
      {
        id: "2",
        name: "Mangekyō Sharingan",
        icon: require("../assets/img/shisui_mangeko.png"),
      },
    ],
    nature_Transformations: [
      { id: "1", name: "Fire Release", icon: require("../assets/img/fire.png") },
      {
        id: "2", name: "Ligthing Release",
        icon: require("../assets/img/lightning.png"),
      },
      { id: "3", name: "Wind Release", icon: require("../assets/img/wind.png") },
      {  id: "4",name: "Yang Release", icon: require("../assets/img/yang.png") },
    ],
  },
];
